### ISSUE TITLE
WCAG Techniques "Official version" link appears to be incorrect

### ISSUE THREAD

**Issue by jribbens** [w3c/wcag#1740]
The official link for "Techniques for WCAG 2.1" appears to be https://www.w3.org/WAI/WCAG21/Techniques/

* The title and heading of this page however say "Techniques for WCAG 2.2", contradicting the URL.
* The "Official link" in the header of the page says https://www.w3.org/WAI/WCAG22/techniques/ which seems to be wrong in two different ways.
* The "Official link" link actually *links* to a different URL from its text, https://www.w3.org/WAI/WCAG22/Understanding/, which appears to be a completely different document.

**Comment by alastc** [comment]
@michael-n-cooper  - I think this is correct on the WCAG 2.1 branch, can you do a publish from that branch please?

**Comment by alastc** [comment]
This has been resolved.

**Comment by jribbens** [comment]
Several of the problems still remain:
* The text of the "Official Version" link says https://www.w3.org/WAI/WCAG21/techniques/, i.e. it has a lower-case `t`. 
* The actual URL linked by that link differs from the text displayed, in that it links to https://www.w3.org/WAI/WCAG21/Understanding/, which appears to be a completely different document.
